### PR TITLE
Final time calculation in `_concatenate_pulses`.

### PR DESCRIPTION
**Pull request by christian512**
The calculation of `final_time` was done by taking the last element of the `tlist` in `compiled_tlist`. However, the elements in `compiled_tlist` are again lists, where the first element is just a list and the second element are the actual times.
E.g. `tlist = [[0.0], np.array([...])]`

 So we have to take the second ( i.e. last) element from that and then the last element to get the largest time.
The previous version sometimes produced errors when using `processor.load_circuit(...)`.

### CODE REVIEW

**Comment by christian512** [comment]
The CI fails due to the error that is fixed in this PR: https://github.com/qutip/qutip-qip/pull/163

**Comment by hodgestar** [comment]
@christian512 Do you have a test we can add for this?

**Comment by BoxiLi** [comment]
This is very strange... I think they should be either all lists or all arrays. Let me have a closer look at it.

**Comment by BoxiLi** [comment]
Yes, you are right. It wasn't showing up because in most of the examples all the sub `tlist`s have the same size and NumPy treat them as a 2D array. 
Let me try to construct a test for this.

@christian512 do you mind if I push to this branch?

**Comment by hodgestar** [comment]
> @christian512 do you mind if I push to this branch?

@BoxiLi Christian is on holiday this week, so I think he is fine with you pushing to this branch at the moment.

**Pull request merged**
