### PR TITLE
Prepare the v0.1.0 release

### PR DESCRIPTION
**Pull request by BoxiLi**
This is the first release so there is not much change or cherry-pick needed. Only the development status.

### CODE REVIEW

**Review by nathanshammah — COMMENTED** [review]
Do you need to change now the `version.txt`?

**Comment by nathanshammah** [comment]
Ah ok is already in setup.cfg.

**Review by nathanshammah — APPROVED** [review]

**Review by hodgestar — APPROVED** [review]
Looks good to me!

**Comment by BoxiLi** [comment]
Some last-time changes in the docstrings are added.

**Pull request merged**
