### PR TITLE
fix circuit plot error for gates with classical controls when reverse_states=False

### PR DESCRIPTION
**Pull request by kpobrien**
For circuits with a classical control and when `reverse_state=False`, the error reported in #220 occurs. This pull request changes the sign of the argument of `\ctrl` when `reverse_state=False`. With this change, the test circuit is plotted without errors:

```python
from qutip_qip.circuit import QubitCircuit
qc = QubitCircuit(1, num_cbits=1, reverse_states=False)
qc.add_gate("X", targets=0, classical_controls=[0])
print(qc.latex_code())
qc.png
```
```
\documentclass[border=3pt]{standalone}
\usepackage[braket]{qcircuit}
\begin{document}
\Qcircuit @C=1cm @R=1cm {
 &  &  \gate{X}  & \qw \\ 
 &  &  \ctrl{-1}  & \qw \\ 
}
\end{document}
```
image

A more complex test case:
```python
from qutip_qip.circuit import QubitCircuit, CircuitSimulator
from qutip_qip.operations import hadamard_transform

qc = QubitCircuit(3, num_cbits=2, reverse_states=False)
qc.user_gates = {"H": hadamard_transform(1)}
qc.add_gate("CNOT", targets=1, controls=2)
qc.add_gate("H", targets=2)
qc.add_measurement("M1", targets=1, classical_store=0)
qc.add_measurement("M2", targets=2, classical_store=1)
qc.add_gate("X", targets=0, classical_controls=0)
qc.add_gate("Z", targets=0, classical_controls=1)
qc.png
```
image

```python
from qutip_qip.circuit import QubitCircuit, CircuitSimulator
from qutip_qip.operations import hadamard_transform

qc = QubitCircuit(3, num_cbits=2, reverse_states=True)
qc.user_gates = {"H": hadamard_transform(1)}
qc.add_gate("CNOT", targets=1, controls=2)
qc.add_gate("H", targets=2)
qc.add_measurement("M1", targets=1, classical_store=0)
qc.add_measurement("M2", targets=2, classical_store=1)
qc.add_gate("X", targets=0, classical_controls=0)
qc.add_gate("Z", targets=0, classical_controls=1)
qc.png
```
image

### CODE REVIEW

**Comment by BoxiLi** [comment]
Thank you! Could you add the simple example to the `tests/test_circuit.py`? Similar to 
https://github.com/qutip/qutip-qip/blob/6a2977ee8cb58d3ac421408677eea96e239e738c/tests/test_circuit.py#L678-L693

**Comment by kpobrien** [comment]
Certainly and thanks for the quick response. Is adding the following code below the function `test_latex_code_teleportation_circuit` what you had in mind? If yes, I'll revise the PR to reflect this. 
```python
    def test_latex_code_classical_controls(self):
        qc = QubitCircuit(1, num_cbits=1, reverse_states=True)
        qc.add_gate("X", targets=0, classical_controls=[0])
        latex = qc.latex_code()
        assert latex == self._latex_template % "\n".join([
            r" &  &  \ctrl{1}  & \qw \\ ",
            r" &  &  \gate{X}  & \qw \\ ",
            "",
        ])

    def test_latex_code_classical_controls_non_reversed(self):
        qc = QubitCircuit(1, num_cbits=1, reverse_states=False)
        qc.add_gate("X", targets=0, classical_controls=[0])
        latex = qc.latex_code()
        assert latex == self._latex_template % "\n".join([
            r" &  &  \gate{X}  & \qw \\ ",
            r" &  &  \ctrl{-1}  & \qw \\ ",
            "",
        ])
```

**Comment by BoxiLi** [comment]
Yes, precisely. Maybe in one test function instead of two.

After being added, these tests will be automatically executed on GitHub. You can also test it locally with `pytest tests` to verify if everything is correct.

**Comment by kpobrien** [comment]
>Yes, precisely. Maybe in one test function instead of two.

Done,  I updated the PR and it passes the tests locally. I see a message "3 workflows awaiting approval", so you may need to approve running the tests on Github.

**Comment by BoxiLi** [comment]
All looks good, thanks for your contribution!

**Pull request merged**
